version: '3.6'
services:

   dicom-cloudtop:
      image: muralikarthikk/try-ohif:0.0.10
      container_name: dicom-cloudtop
      ports:
        - 3000:80
      deploy:
        resources:
          limits:
            cpus: '0.60'
            memory: 5000M
          reservations:
            cpus: '0.60'
            memory: 5000M
