version: '3.6'
services:

   cloudtop:
      image: heliumdatastage/renci-guacamole-vnc:use-all-defaults
      container_name: cloudtop
      volumes:
         - TYCHO_NFS/cloud-top:/usr/local/renci/data
      entrypoint: /init
      ports: 
         - 8080:8080

   viewer:
      image: ohif/viewer:v1.1.14.3708
      container_name: viewer
      volumes:
         - TYCHO_NFS/cloud-top:/mounts
         - TYCHO_NFS/cloud-top:/etc/nginx/conf.d
      environment:
         - MONGO_URL=mongodb://mongo:27017/ohif
         - APP_CONFIG=/mounts/app-config.js
      depends_on:
         - mongo
         - orthanc
      ports:
         - "3000:80"

   orthanc:
      image: jodogne/orthanc-plugins:latest
      container_name: orthanc
      depends_on:
         - postgres
      volumes:
         - TYCHO_NFS/cloud-top:/etc/orthanc
      ports:
         - "8042:8042"
         - "4242:4242"
      securityContext:
          privileged: true

   mongo:
      image: mongo:latest
      container_name: mongo
      ports:
         - "27017:27017"
      volumes:
        - mongodata:/data/db

   postgres:
      image: heliumdatastage/postgres:stage
      container_name: postgres
      volumes:
        - pgdata:/var/lib/postgresql
      environment:
        - POSTGRES_DB=orthanc
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres-orthanc
      ports:
         - "5432:5432"
      securityContext:
          privileged: true
     
