version: '3.6'
services:

   dicom-cloudtop:
      image: ohif/viewer:latest
      container_name: dicom-cloudtop
      ports:
        - 8081:8080
      deploy:
        resources:
          limits:
            cpus: '0.60'
            memory: 5000M
          reservations:
            cpus: '0.60'
            memory: 5000M
