# .dockstore.yml for JBrowse
version: 1.1
service:
  type: docker-compose
  name: JBrowse
  author:
  description: |
    JBrowse is a fast, scalable genome browser built completely with JavaScript and HTML5.
    It can run on your desktop, or be embedded in your website.
  # These are files the Dockstore will index. They will be directly downloadable from Dockstore
  files:
     - docker-compose.yml
     - healthcheck.sh
     - port.sh
     - prepare_refdata.sh
     - stand_up.sh
     - stop.sh
     - GRCh37.json

  scripts:
    # The scripts preprovision, prestart, start, poststart, and postprovision will be executed in order.
    # The only script required to have a value is start.

    # Before any provisioning
    preprovision:

    # After provisioning, before starting the service
    prestart: prepare_refdata.sh

    # Starts the service
    start: stand_up.sh

    # After the service has started
    poststart:

    # After the service has started. For multiple provisionings, e.g., the user may decide to add more data later.
    postprovision:

    # Returns the port the service is exposing. Can be used by a client to know what port to proxy
    port: port.sh

    # Returns an exit code of 0 if service is running
    healthcheck: healthcheck.sh

    # Stops the service
    stop: stop.sh

  environment:
    JBROWSE_NAME:
        default: jbrowse
        description: The name of the container.
    HTTP_PORT:
        default: "3000"
        description: The host port that JBrowse exposes.

  # Data are files that are provisioned locally for the service. Each key is a dataset name,
  # and each dataset can contain 1 to n files
  data:
    # The name of a dataset, can be anything
    dataset_1:
        targetDirectory: data
        files:
            reference:
                description: A reference sequence

