version: '3'
services:
  jbrowse:
    image: quay.io/coverbeck/jbrowse:feature_service
    container_name: ${JBROWSE_NAME:-jbrowse}
    command: utils/jb_run.js -p 3000
    ports:
    - "${HTTP_PORT:-3000}:3000"
    volumes:
    - ./data:/jbrowse/data
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 64000M
        reservations:
          cpus: '1'
          memory: 4000M 