---
# Docker compose formatted system.
version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - $HOST_PORT:80
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 20M
