version: "3.0"
services:
  nextflow:
    image: bentsherman/nextflow-api
    env:
      - NXF_EXECUTOR=k8s
    entrypoint:
      - /bin/bash
      - -c
      - cd /opt/nextflow-api; scripts/startup.sh
    ports:
      - $HOST_PORT:8080
    volumes:
      - TYCHO_NFS/deepgtex-prp:/workspace
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4Gi
