version: "3.0"
services:
  nextflow:
    image: cbmckni/nextflow-api:latest
    env:
      - NXF_EXECUTOR=k8s
    entrypoint:
      - /bin/bash
      - -c
      - ./scripts/db-startup.sh && cd /opt/nextflow-api; python3 bin/server.py --db-hostname=0.0.0.0
    ports:
      - $HOST_PORT:8080
    #volumes:
    #  - pvc://deepgtex-prp:/workspace
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4Gi
