---
# Docker compose formatted system.
version: "3"
services:
  rstudio-server:
    image: heliumdatastage/rstudio-server:tycho
    entrypoint:
      - /bin/bash
      - -c
      - /usr/lib/rstudio-server/bin/rserver --server-daemonize=0 --auth-none=1
    environment:
      - DISABLE_AUTH=true
    ports:
      - 8787:8787
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 150Mi
        reservations:
          cpus: '0.5'
          memory: 150Mi
