---
# Docker compose formatted system.
version: "3"
services:
  rstudio-server:
    image: heliumdatastage/rstudio-server:cca-v0.0.1
    environment:
      - DISABLE_AUTH=true
    ports:
      - 8787:8787
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 150Mi
        reservations:
          cpus: '0.5'
          memory: 150Mi
