---
# Docker compose formatted system.
version: "3"
services:
  rstudio-server:
    image: heliumdatastage/rstudio-server:all-v0.0.6
    environment:
      - DISABLE_AUTH=true
    ports:
      - 8787:8787
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 800M
        reservations:
          cpus: '0.5'
          memory: 800M
