---
# Docker compose formatted system.
version: "3"
services:
  rstudio-server:
    image: heliumdatastage/rstudio-server:tycho
    environment:
      - DISABLE_AUTH=true
    ports:
      - 8787:8787
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 20M
