---
# Docker compose formatted system.
version: "3"
services:
  jupyter-datascience:
    image: jupyter/datascience-notebook
    entrypoint: start.sh jupyter lab --LabApp.token= --NotebookApp.base_url=${NB_PREFIX}
    ports:
      - $HOST_PORT:8888
    volumes:
      - TYCHO_NFS/cloud-top:/mydata
#      - ./:/mydata1
#      - ./home:/mydata2
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 1000M
        reservations:
          cpus: '0.10'
          memory: 1000M
