---
# Docker compose formatted system.
# NOTE: NB_PREFIX has to be set to "/" as an environment variable if running locally. 
# If running via tycho from CommonsShare AppStore, tycho will set the variable.
version: "3"
services:
  jupyter-ds:
    image: heliumdatastage/jupyter-datascience:v0.0.3
    entrypoint:
      - /bin/bash
      - -c
      - start.sh jupyter lab --LabApp.token= --ip="*" --NotebookApp.base_url=${NB_PREFIX} --NotebookApp.allow_origin="*"
    ports:
      - 8888:8888
    volumes:
      - pvc://cloud-top/mydata:/mydata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1000M
        reservations:
          cpus: '0.50'
          memory: 1000M
