---
# Docker compose formatted system.
version: "3"
services:
  jupyter-datascience:
    image: jupyter/datascience-notebook
    entrypoint: start.sh jupyter lab --LabApp.token=
    ports:
      - $HOST_PORT:8888
    volumes:
      - TYCHO_NFS/deepgtx-prp:/mydata
#      - ./:/mydata1
#      - ./home:/mydata2
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 20M
