version: "3.6"
services:
  kstars:
    image: helxplatform/cloudtop-kstars:0.1.1
    container_name: kstars
    env:
     - VNC_RESOLUTION=1980x1024
    entrypoint: /init
    ports:
      - 8080:8080
    volumes:
      - pvc://cloud-top:/data
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8000M
        reservations:
          cpus: '0.5'
          memory: 2000M
