# Docker compose formatted system.
version: "3"
services:
  hail:
    image: heliumdatastage/helx-hail:latest
    ports:
      - 8000:8000
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 5G
        reservations:
          cpus: '1'
          memory: 5G
