# Docker compose formatted system.
version: "3"
services:
  hail:
    image: heliumdatastage/helx-hail:v0.0.1
    ports:
      - 8000:8000
    entrypoint:
      - /bin/bash
      - -c
      - start.sh jupyter lab --LabApp.token= --ip="*" --port=8000 --NotebookApp.base_url=${NB_PREFIX} --NotebookApp.allow_origin="*"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 5G
        reservations:
          cpus: '1'
          memory: 5G
