version: '3.6'
services:

   dicom-gh:
      image: heliumdatastage/cloudtop-ohif:develop-latest
      container_name: dicom-gh
      environment:
      entrypoint: /init
      ports: 
        - 8080:8080
      volumes:
         - pvc://helx-sidecar-test/sidecar:/sidecar
      deploy:
        resources:
          limits:
            cpus: '1'
            memory: 1G
          reservations:
            cpus: '1'
            memory: 1G
