# .dockstore.yml for Xena
version: 1.1
service:
  type: docker-compose
  name: UCSC Xena Browser
  author: UCSC Genomics Institute
  description: |
    The UCSC Xena browser is an exploration tool for public and private,
    multi-omic and clinical/phenotype data.
    It is recommended that you configure a reverse proxy to handle HTTPS
  # These are files the Dockstore will index. They will be directly downloadable from Dockstore
  files:
     - docker-compose.yml 
     - README.md
     - stand_up.sh
     - load.sh
     - port.sh
     - stop.sh

  scripts:
    # The scripts preprovision, prestart, start, poststart, and postprovision will be executed in order.
    # The only script required to have a value is start.
    
    # Before any provisioning
    preprovision: 
    
    # After provisioning, before starting the service
    prestart: 
     
    # Starts the service
    start: bash stand_up.sh 
    
    # After the service has started
    poststart: 
    
    # After the service has started. for multiple provisionings, e.g., the next day
    postprovision: bash load.sh 

    # Returns the port the service is exposing. Can be used by a client to know what port to proxy
    port: bash port.sh
    
    # Returns an exit code of 0 if service is running successfully.
    healthcheck: 
    
    # Stops the service
    stop: bash stop.sh 

  # Parameters are passed to the scripts as environment variables. They are service
  # specific, i.e., the service create decides which values to make parameterizable.
  parameters:
    # The name of the parameter, can be anything that is a valid environment variable name
    httpPort: 
        # An optional default value
        default: "7222"
        # A description that tools can use to prompt the user
        description: The host's HTTP port. The default is 7222.

  # Data are files that are provisioned locally for the service. Each key is a dataset,
  # where the dataset can contain 1 to n files
  data:
    targetDirectory: xena/files # Can override this at the dataset and/or individual file level.
    dataset_1:
        # The optional property indicates whether there can be multiple sets of files.
        # If not set, or false, then only the one set of files can be specified
        multiple: true
        
        # Can optionally override targetDirectory here
        # targetDirectory:
       
        # The files property is required for datasets. It will contain one or more
        # files. In this example, Xena expects pairs of files to uploaded, the data
        # and the metadata.
        files:
            tsv:
                description: Data for Xena in TSV format
            metadata:
                description: The metadata, in JSON format, that corresponds to the data
