# .dockstore.yml for Xena
version: 1.1
service:
  type: docker-compose
  name: UCSC Xena Browser
  author: UCSC Genomics Institute
  description: |
    The UCSC Xena browser is an exploration tool for public and private,
    multi-omic and clinical/phenotype data.
    It is recommended that you configure a reverse proxy to handle HTTPS
  # These are files the Dockstore will index. They will be directly downloadable from Dockstore
  files:
     - docker-compose.yml
     - README.md
     - stand_up.sh
     - load.sh
     - port.sh
     - stop.sh

  scripts:
    # The scripts preprovision, prestart, start, poststart, and postprovision will be executed in order.
    # The only script required to have a value is start.

    # Before any provisioning
    preprovision:

    # After provisioning, before starting the service
    prestart:

    # Starts the service
    start: stand_up.sh

    # After the service has started
    poststart:

    # After the service has started. For multiple provisionings, e.g., the user may decide to add more data a week later.
    postprovision: load.sh

    # Returns the port the service is exposing. Can be used by a client to know what port to proxy
    port: port.sh

    # Returns an exit code of 0 if service is running successfully.
    healthcheck:

    # Stops the service
    stop: stop.sh

  # Parameters are passed to the scripts as environment variables. They are service
  # specific, i.e., the service creator decides which values to make parameterizable.
  parameters:
    # The name of the parameter, can be anything that is a valid environment variable name
    httpPort:
        # An optional default value
        default: "7222"
        # A description that tools can use for prompting the a user.
        description: The host's HTTP port. The default is 7222.

  # Data are files that are provisioned locally for the service. Each key is a dataset name,
  # where the dataset can contain 1 to n files
  data:
    dataset_1:
        targetDirectory: xena/files # Can override this at the individual file level.

        # The optional property indicates whether there can be multiple sets of files.
        # If not present, or false, then only one set of files can be specified.
        # In this case, Xena can accept multiple pairs of files, so it is true.
        multiple: true

        # The files property is required for datasets. It will contain one or more files.
        files:
            tsv:
                description: Data for Xena in TSV format

                # Could override targetDirectory here, but since all files go into xena/files, no need
                # targetDirectory:
            metadata:
                description: The metadata, in JSON format, that corresponds to the data
