# .dockstore.yml for Xena
version: 1.1
service:
  type: docker-compose
  name: UCSC Xena Browser
  author: UCSC Genomics Institute
  description: |
    The UCSC Xena browser is an exploration tool for public and private,
    multi-omic and clinical/phenotype data.
    It is recommended that you configure a reverse proxy to handle HTTPS
  # These are files the Dockstore will index. They will be directly downloadable from Dockstore
  files:
     - docker-compose.yml
     - README.md
     - stand_up.sh
     - load.sh
     - port.sh
     - stop.sh

  scripts:
    # The scripts preprovision, prestart, start, poststart, and postprovision will be executed in order.
    # The only script required to have a value is start.

    # Before any provisioning
    preprovision:

    # After provisioning, before starting the service
    prestart:

    # Starts the service
    start: stand_up.sh

    # After the service has started
    poststart:

    # After the service has started. For multiple provisionings, e.g., the user may decide to add more data later.
    postprovision: load.sh

    # Returns the port the service is exposing. Can be used by a client to know what port to proxy
    port: port.sh

    # Returns an exit code of 0 if service is running successfully.
    healthcheck:

    # Stops the service
    stop: stop.sh

  # Items in this section are passed to the scripts as environment variables.
  # The names must be valid enviornment variable names.
  environment:
    httpPort: # The name of the environment variable
        default: "7222" # An optional default value
        # A description that tools can use for prompting a user.
        description: The host's HTTP port. The default is 7222.

  # Data are files that are provisioned locally for the service. Each key is a dataset name,
  # and each dataset can contain 1 to n files
  data:
    # The name of a dataset, can be anything
    dataset_1:
        # The location on the local system where files should be downloaded to. This
        # can be overriden if desired on an individual file level.
        # In this case, Xena requires files to be located in the subdirectory xena/files
        # relative to where Xena is running.
        targetDirectory: xena/files 

        # The files property is required for datasets. It contains one or more files.
        # The sets of files can be repeated. In the sample xena-all.json, there are
        # 3 pairs of tsv/metadata files.
        files:
            tsv:
                description: Data for Xena in TSV format

                # Could override targetDirectory here, but since all files go into xena/files, no need
                # targetDirectory:
            metadata:
                description: The metadata, in JSON format, that corresponds to the previous tsv file
