version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - 8080:8080
    volumes:
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
