version: "3"
services:
 filebrowser:
  image: hurlenko/filebrowser
  ports:
   - 8080:8080
  entrypoint:
   - /bin/sh
   - -c
   - /filebrowser config init --auth.method=noauth && /filebrowser --root="/home" --address=0.0.0.0 --database=/config/filebrowser.db
