version: "3"
services:
 filebrowser:
  image: hurlenko/filebrowser
  ports:
   - 8080:8080
  entrypoint:
   - /bin/sh
   - -c
   - rm -rf /home/${USER_NAME}/filebrowser.db && /filebrowser config init && chown -R 1000:1000 ./filebrowser.db && /filebrowser config set --auth.method=noauth --database=/home/${USER_NAME}/filebrowser.db && /filebrowser --noauth --root="/home" --address=0.0.0.0
  deploy:
    resources:
      limits:
        cpus: '0.5'
        memory: 2000M
      reservations:
        cpus: '0.5'
        memory: 2000M 
