version: "3.6"
services:
  imagej:
    image: heliumdatastage/cloudtop-imagej:latest
    container_name: imagej
    env:
     - VNC_RESOLUTION=1920x1200
    entrypoint: /init
    ports:
      - 8080:8080
    volumes:
      - pvc://cloud-top:/data
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16000M
        reservations:
          cpus: '4'
          memory: 16000M
