version: "3.6"
services:
  imagej:
    image: heliumdatastage/renci-guacamole-vnc:test
    container_name: imagej
    entrypoint: /init
    ports:
      - 8080:8080
    volumes:
      - pvc:/usr/local/renci/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 5000M
        reservations:
          cpus: '0.50'
          memory: 5000M
