version: "3.6"
services:
  imagej:
    image: heliumdatastage/renci-guacamole-vnc:test
    container_name: imagej
    entrypoint: /init
    ports:
      - 8080:8080
    volumes:
      - TYCHO_NFS/cloud-top:/usr/local/renci/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 10000M
